package entities;
// Generated 23/03/2016 01:44:51 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol", schema = "public")
public class Rol implements java.io.Serializable {

	private long rolId;
	private String nombrerol;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Rol() {
	}

	public Rol(long rolId, String nombrerol) {
		this.rolId = rolId;
		this.nombrerol = nombrerol;
	}

	public Rol(long rolId, String nombrerol, Set<Usuario> usuarios) {
		this.rolId = rolId;
		this.nombrerol = nombrerol;
		this.usuarios = usuarios;
	}

	@Id

	@Column(name = "rol_id", unique = true, nullable = false)
	public long getRolId() {
		return this.rolId;
	}

	public void setRolId(long rolId) {
		this.rolId = rolId;
	}

	@Column(name = "nombrerol", nullable = false)
	public String getNombrerol() {
		return this.nombrerol;
	}

	public void setNombrerol(String nombrerol) {
		this.nombrerol = nombrerol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
